server:
  port: 8080
---
spring:
  cloud:
    gateway:
      default-filters:
        - name : JwtRequestFilter
          args:
            baseMessage: validation Token Start..
      routes:
        - id: post-svc
          uri: http://localhost:8082/
          predicates:
            - Path=/**